# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'f7a85630-a98a-4d43-8832-fd9d8659504a'
  imageRepository: 'asciibackstage'
  containerRegistry: 'gallowayacr12345.azurecr.io'
  dockerfilePath: '**/packages/backend/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'gallowayacr12345435253e0-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: CI
  displayName: CI
  jobs:
  - job: CI
    displayName: CI 
    timeoutInMinutes: 20 
    pool: mypool
    steps:
    - bash: yarn install --frozen-lockfile
    - bash: yarn tsc
    - bash: yarn build 
    - bash: docker image build . -f packages/backend/Dockerfile --tag backstage
    - bash: docker image tag backstage $(dockerRegistryServiceConnection)/$(imageRepository):$(tag)
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: push
        tags: $(tag)
